export const NODE_ENVIRONMENT_MODE = {
  DEVELOPMENT: 'development',
  PRODUCTION: 'production',
  TEST: 'test',
};

export const DEFAULT_TARGET_BRANCH = 'main';

export const STATUS_CODE = {
  OK: 200,
  NON_AUTHORITATIVE_INFORMATION: 203,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  UNAUTHORIZED_ACCESS: 401,
  INTERNAL_SERVER_ERROR: 500,
};

export const ERROR_MESSAGE = {
  INTERNAL_SERVER_ERROR: 'Something went wrong',
};

export const VERSION_CONTROL_SYSTEM = {
  AZURE_DEVOPS: 'AZURE_DEVOPS',
};

Object.freeze(NODE_ENVIRONMENT_MODE, STATUS_CODE, ERROR_MESSAGE, VERSION_CONTROL_SYSTEM);
