export const QUERY_KEY = {
  CODE_REVIEW: "CODE_REVIEW_METRICS",
  TRUNK_BASED_TOTAL_BRANCHES: "TRUNK_BASED_METRICS_TOTAL_BRANCHES",
  TRUNK_BASED_ACTIVE_BRANCHES: "TRUNK_BASED_METRICS_ACTIVE_BRANCHES",
  TRUNK_BASED_PULL_REQUESTS: "TRUNK_BASED_METRICS_PULL_REQUESTS",
  TRUNK_BASED_BRANCH_COMMITS: "TRUNK_BASED_BRANCH_COMMITS",
  CLIENT_FILTERS: "CLIENT_FILTERS",
};
