name: Development Package

on:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    env:
      working-directory: server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read node version
        id: nvmrc
        uses: juliangruber/read-file-action@v1
        with:
          path: ./${{ env.working-directory }}/.nvmrc

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvmrc.outputs.content }}

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.working-directory }}

      - name: Run client build
        run: npm run build:client
        working-directory: ${{ env.working-directory }}

      - name: Run docker build
        run: npm run build:docker
        working-directory: ${{ env.working-directory }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-package-software-practices-metrics-tool
          path: ./${{ env.working-directory }}/software-practices-metrics-tool.zip

  electron-build:
    runs-on: windows-latest

    env:
      server-working-directory: server
      electron-working-directory: server\release-to-production\electron-package

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read node version
        id: nvmrc
        uses: juliangruber/read-file-action@v1
        with:
          path: ./${{ env.server-working-directory }}/.nvmrc

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvmrc.outputs.content }}

      - name: Install server dependencies
        run: npm install
        working-directory: ${{ env.server-working-directory }}

      - name: Install electron dependencies
        run: npm install
        working-directory: ${{ env.electron-working-directory }}

      - name: Run client build
        run: npm run build:client
        working-directory: ${{ env.server-working-directory }}

      - name: Run electron build
        run: npm run build
        working-directory: ${{ env.electron-working-directory }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer-software-practices-metrics-tool
          path: ./${{ env.electron-working-directory }}/software-practices-metrics-tool.zip
