name: Server CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  server-test:
    runs-on: ubuntu-latest

    env:
      working-directory: server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.1"

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.working-directory }}

      - name: Check format
        run: npm run format-check
        working-directory: ${{ env.working-directory }}

      - name: Check lint
        run: npm run lint
        working-directory: ${{ env.working-directory }}

      - name: Run tests
        run: npm run test-ci
        working-directory: ${{ env.working-directory }}
